---
title: "P8 - Data gathering"
author: "Laust Visby Andreasen"
date: "2024-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(tidyverse)
```

```{r}
APIstock <- "https://api.polygon.io/v2/aggs/ticker/O:AAPL221104C00"
APItid <- "/range/1/minute/2022-10-04/2022-11-03?adjusted=true&sort=asc&limit=50000&api"
APIkey <- "Key=CBQouP6k8C92g2XWhofZB5PCGgxI6lOk"
startprice <- 100
```


```{r}
API<- paste(APIstock,as.character(as.integer(startprice*1000)),APItid, APIkey, sep = "")
raw <- jsonlite::fromJSON(API)

vw <- raw$results$vw
t <- raw$results$t
assign(paste0("df", startprice), data.frame(vw,t))
startprice <- startprice + 1
```

```{r}
df_list <- list(df100, df105, df110, df115, df120, df125, df126, df127, df128, df129, df130, df131, df132, df133, df134, df135, df136, df137, df138, df139, df140, df141, df142, df143, df144, df145, df146, df147, df148, df149, df150, df155, df160, df165, df170, df175, df180, df185, df190, df195, df200)
```

```{r}
df <- Reduce(function(x,y) merge(x,y, all = TRUE, by = "t"), df_list)
```

```{r}
K_list <- list("K100", "K105", "K110", "K115", "K120", "K125", "K126", "K127", "K128", "K129", "K130", "K131", "K132", "K133", "K134", "K135", "K136", "K137", "K138", "K139", "K140", "K141", "K142", "K143", "K144", "K145", "K146", "K147", "K148", "K149", "K150", "K155", "K160", "K165", "K170", "K175", "K180", "K185", "K190", "K195", "K200")
```


```{r}
for (i in 1:length(K_list)) {
  colnames(df)[i+1] <- K_list[i]
}
```


```{r}
write.csv(df, "CallApple.csv")
```

hent call filen
```{r}
#call <- read.csv("/Users/christiantaulbjerg/Documents/GitHub/F2024/CallApple.csv")
call <- read.csv("C:\\Users\\Bruger\\Desktop\\F2024\\CallApple.csv")
```


STOCK
```{r}
SAPI <- "https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2022-10-04/2022-11-03?adjusted=true&sort=asc&limit=50000&apiKey=CBQouP6k8C92g2XWhofZB5PCGgxI6lOk"
Sraw <- jsonlite::fromJSON(SAPI)
```

Find riskfree rate r
```{r}
#Fetch Treasury bond yields from FRED (Federal Reserve Economic Data)
getSymbols("DGS3MO", src = "FRED", from = "2022-10-11", to = "2022-11-03")


#Extract data
treasury_yield <- DGS3MO[, "DGS3MO"]

#Calculate risk-free rate as the 10-year Treasury bond yield
risk_free_rate <- tail(treasury_yield, 1) / 100

print(risk_free_rate)
r <- 0.0425
```

```{r}
S <- Sraw$results$c
t <- Sraw$results$t
S0 <- data.frame(S,t)
```

```{r}
for (i in 1:length(call$X)) {
  call[i,1] <- r
}

names(call)[1] <- "r"
```

```{r}
FULLdf <- left_join(call, S0, by = "t")
```


```{r}
write.csv(FULLdf, "Data_w_S_and_r.csv")
```

```{r}
for (i in 1:length(FULLdf$t)) {
  FULLdf[i,2] <- (FULLdf[i,2] - 1664890200000)/60000
}
```

```{r}
write.csv(FULLdf, "Data_t_in_min.csv")
```

